---
title: "Desafios das aulas"
output:
  html_document:
    toc: true
    code_folding: show
    toc_depth: 2
    toc_float:
      collapsed: no
      smooth_scroll: no
---

```{r setup, include=FALSE, cache=FALSE}
#source("setup_knitr.R")
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA,
                      warning = FALSE,
                      message = FALSE)
```
 Abaixo segue os desafios dados em aula. Sugere-se realizá-los para que o aluno consiga absorver melhor o conteúdo dado nas aulas síncronas e também
servirá para completar a carga horária do curso e assim obter o certificado.

## **Desafio 1**

Defina um oobjetivo que queira resolver por meio de um modelo de *machine learning*. Pode ser um problema que queira resolver de fato em seu ambiente acadêmico ou profissional ou crie algo a ser resolvido em possa ter os dados necessários para resolvê-lo.

Para ajudar a definir seu objetivo e saber onde quer chegar, responda a seguintes perguntas:

- 1- Qual é o problema?

- 2- Por que o problema precisa ser resolvido?

- 3- Como eu resolvo o problema?


Após entender o problema, responda as perguntas referentes aos dados:

- 1 -Quais os tipos de dados você tem disponível?

- 2- Quais dados desejáveis não estão disponíveis?

- 3- Quais dados você não precisa para resolver o problema?

Colete seus dados e os armazene para a resolução dos próximos desafios.

Por fim, elabore um diagrama resumindo seu objetivo e dados como apresentado em aula (Slide12 da aula1).

## **Desafio 2**


### Com os dados coletados no desafio anterior, faça:

- Engenharia de características

  1. Faça uma análise exploratória de seus dados. Com gráficos e medidas descritivas;


  2. Crie novas características com base em outras já presente no conjunto de dados;

  
  3. Se houver dados faltantes, identifique-os e use dois tipos de imputação e compare os resultados;

  4. Se houver dados desbalanceados em sua label(Y), utilize a ténica *SMOTE* ou redução da classe majoritária;

  5. Faça uma matriz de correlação linear, interprete e decida se irá excluir ou não alguma característica.

## **Desafio 3**

- Com seus dados, aplique uma análise de componentes principais


## **Desafio 4**

**Com os dados coletados no desafio 1, faça:**

- Uma análise utilizando o algoritmo *K-means*
 
<br>
 
-  Um modelo de aprendizado supervisionado.
 
<br>
 
- Compare seus resultados utilizando os métodos de árvores.

   1. *Random forests.*
   
   2. *Gardient Boosting Machine.*

<br>
 
- Se for um problema de classificação, compare também com regressão logística ou multinomial.
 
<br>
 
- Se for um problema de regressão, compare também com regressão linear.
 
<br> 
 
- Em ambos os casos decida por um dos modelos e explique a sua escolha.



## **Desafio 5**

- Com os gerados no desafio 4, tente melhorar suas predições com as técnicas apresentadas na aula de hoje.
 
<br> 
 
- Faça uma tabela com as novas métricas de desempenho comparando omodelo antigo e novo.
 
<br> 
 
- Faça um breve relatório contando a história dos seus dados e os resultados do modelo que escolheu.